# Numpy: ProblemSet

In [ ]:
import sys
sys.path.append("./utils/student_function/")

## Problema 1

Dados dos arreglos X y Y, construir la matriz de Cauchy $$C\:\:[ C_{ij}=\:\: \frac{1}{X_i-Y_j} ]$$

retornar el determinante de la matriz

>- Matriz de Cauchy: https://en.wikipedia.org/wiki/Cauchy_matrix , las entradas de la matriz, son el resultado de la resta de los arreglos en la posición correspondiente, donde las Filas equivalen a X y las columnas a Y. Asegurese de que no realice divisiones por 0. (Pista, consulte la función substract.outer de numpy) 

### Ejemplo de Ejecución

``` python

>>>X = np.arange(10)
>>>Y = X + 0.3
>>>cauchy(X,Y)
547032.86592945794

```

### Solución:

In [ ]:
%%writefile utils/student_function/student_PS2_NUMPY_1.py
## Ejercicio del estudiante

import numpy as np 

def cauchy(X,Y):
   
    #tu codigo aquí
    
    return determinante


### Prueba manuealmente tu respuesta

In [ ]:
import student_PS2_NUMPY_1 as st
reload(st)
import numpy as np
X = np.arange(10)
Y = X + 0.3
st.cauchy(X,Y)


### Ejecuta el corrector automático:

In [ ]:
!./run CHECK_SOLUTION PS2_NUMPY_1

## Problema 2

Dado un arreglo X, hallar el valor más cercano a un escalar dado V, retornar su indice en el arreglo  

### Ejemplo Ejecución

```python

>>>X=np.arange(25,55,2)
>>>v=34
>>>minimo(X,v)
4
```

### Solución

In [ ]:
%%writefile utils/student_function/student_PS2_NUMPY_2.py
## Ejercicio del estudiante

import numpy as np 

def minimo(X,v):
    #aqui tu codigo
    index= 
    
    return index
    


### Prueba manuealmente tu respuesta

In [ ]:
import student_PS2_NUMPY_2 as st
reload(st)
X=np.arange(25,55,2)
v=34
st.minimo(X,v)

### Ejecuta el corrector automático:

In [ ]:
!./run CHECK_SOLUTION PS2_NUMPY_2

## Problema 3

Dada una matriz, desarrolle un programa que retorne otra de igual dimensiones y en la que se le reste a cada componente, la media aritmética de su respectiva fila.

### Ejemplo de Ejecución

```python

>>>a = [[1, 2, 3], [4, 5, 6],[7,8,9]]
>>>X = np.array(a)
>>>print X
[[1 2 3]
 [4 5 6]
 [7 8 9]]
>>> print media(X)
array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])



```

### Solución

In [ ]:
%%writefile utils/student_function/student_PS2_NUMPY_3.py
## Ejercicio del estudiante

import numpy as np


def media(X):
    #tu codigo aquí


### Prueba manuealmente tu respuesta

In [ ]:
import student_PS2_NUMPY_3 as st
reload(st)
a = [[1, 2, 3], [4, 5, 6],[7,8,9]]
X = np.array(a)
print X
print st.media(X)



### Ejecuta el corrector automático:

In [ ]:
!./run CHECK_SOLUTION PS2_NUMPY_3

## Problema 4

Para este ejercicio retorne en un arreglo, la diagonal del producto de dos matrices dadas.

### Ejemplo de Ejecución

```python

>>>A=[[ 0.74019211,  0.88074775,  0.76313766,  0.16401307,  0.79100838,  0.55012263,
   0.52715895,  0.10473314 , 0.32350678  ,0.10636768],
 [ 0.60191586,  0.19951451 , 0.30253232  ,0.20650427 , 0.79079405 , 0.88890474,
   0.02091529 , 0.06900835 , 0.19961579  ,0.45072254],
 [ 0.12305539 , 0.80427841 , 0.28039939  ,0.44587499 , 0.22792054 , 0.15380323,
   0.53475777 , 0.2329996  , 0.96797348  ,0.82400304],
 [ 0.72238524 , 0.21711033 , 0.80644066  ,0.53411037 , 0.29574619 , 0.28531133,
   0.08859403  ,0.75136371 , 0.47861943  ,0.11314524],
 [ 0.87248516 , 0.05968816 , 0.03220045  ,0.55847246 , 0.40362461 , 0.54408517,
   0.82325408 , 0.61511986 , 0.1480684   ,0.17169693]]

>>>B=[[ 0.5550068 ,  0.08223711,  0.05259033, 0.35471869,  0.19791947],
 [ 0.55743724  ,0.82923066  ,0.95146065  ,0.30236612 , 0.40422403],
 [ 0.79473269  ,0.2517258   ,0.78367486  ,0.03618329 , 0.31310786],
 [ 0.93932005  ,0.5373381   ,0.77710968  ,0.77713596 , 0.4513889 ],
 [ 0.0490389   ,0.21339475  ,0.60761344  ,0.26668217 , 0.00566334],
 [ 0.16992835  ,0.009103    ,0.57721662  ,0.30618822 , 0.38424874],
 [ 0.64616497  ,0.49037448  ,0.86234425  ,0.05965279 , 0.31444925],
 [ 0.65539184  ,0.86174556  ,0.01188851  ,0.84005788 , 0.48375559],
 [ 0.4156407   ,0.30756694  ,0.81141294  ,0.10472866 , 0.60378635],
 [ 0.41379741  ,0.86851756  ,0.22183539  ,0.00555388 , 0.38982601]]

>>>diagonal(A,B)
 [2.38234622,  1.10148379,  2.99734642,  1.61960306,  1.38310249]

```

### Solución

In [ ]:
%%writefile utils/student_function/student_PS2_NUMPY_4.py
## Ejercicio del estudiante

import numpy as np 
def diagonal(A,B):
    #aqui tu codigo
    
    producto=
    
    diagonal=
    
    return diagonal



### Prueba manuealmente tu respuesta

In [ ]:
import student_PS2_NUMPY_4 as st
reload(st)
A=[[ 0.74019211,  0.88074775,  0.76313766,  0.16401307,  0.79100838,  0.55012263,
   0.52715895,  0.10473314 , 0.32350678  ,0.10636768],
 [ 0.60191586,  0.19951451 , 0.30253232  ,0.20650427 , 0.79079405 , 0.88890474,
   0.02091529 , 0.06900835 , 0.19961579  ,0.45072254],
 [ 0.12305539 , 0.80427841 , 0.28039939  ,0.44587499 , 0.22792054 , 0.15380323,
   0.53475777 , 0.2329996  , 0.96797348  ,0.82400304],
 [ 0.72238524 , 0.21711033 , 0.80644066  ,0.53411037 , 0.29574619 , 0.28531133,
   0.08859403  ,0.75136371 , 0.47861943  ,0.11314524],
 [ 0.87248516 , 0.05968816 , 0.03220045  ,0.55847246 , 0.40362461 , 0.54408517,
   0.82325408 , 0.61511986 , 0.1480684   ,0.17169693]]

B=[[ 0.5550068 ,  0.08223711,  0.05259033, 0.35471869,  0.19791947],
 [ 0.55743724  ,0.82923066  ,0.95146065  ,0.30236612 , 0.40422403],
 [ 0.79473269  ,0.2517258   ,0.78367486  ,0.03618329 , 0.31310786],
 [ 0.93932005  ,0.5373381   ,0.77710968  ,0.77713596 , 0.4513889 ],
 [ 0.0490389   ,0.21339475  ,0.60761344  ,0.26668217 , 0.00566334],
 [ 0.16992835  ,0.009103    ,0.57721662  ,0.30618822 , 0.38424874],
 [ 0.64616497  ,0.49037448  ,0.86234425  ,0.05965279 , 0.31444925],
 [ 0.65539184  ,0.86174556  ,0.01188851  ,0.84005788 , 0.48375559],
 [ 0.4156407   ,0.30756694  ,0.81141294  ,0.10472866 , 0.60378635],
 [ 0.41379741  ,0.86851756  ,0.22183539  ,0.00555388 , 0.38982601]]

st.diagonal(A,B)

### Ejecuta el corrector automático:

In [ ]:
!./run CHECK_SOLUTION PS2_NUMPY_4

## Problema 5

Considere un arreglo de tamaño arbitrario, desarrolle un método para retornar un sub arreglo de tamaño dado y centrado en un valor deseado.

### Ejemplo de Ejecución

```python

>>>X=np.array([ 0.79035627,  0.08409479,  0.57376371,  0.8449833 ,  0.63291871,  0.78611748,
  0.65485656  ,0.6580865   ,0.80133703  ,0.6094324   ,0.62010416  ,0.98148802,
  0.70262324  ,0.42894768  ,0.70470542  ,0.37187055  ,0.05427004  ,0.50294194,
  0.84034571  ,0.00586813])
>>>c=10
>>>l=5

>>>subArray(X,c,l)
[0.80133703, 0.6094324, 0.62010416, 0.98148802, 0.70262324]

```

### Solución

In [ ]:
%%writefile utils/student_function/student_PS2_NUMPY_5.py
## Ejercicio del estudiante

import numpy as np 

def subArray(X,c,l): #X: arreglo, c: centro, l, longitud

    #tu codigo aqui
    
    subArreglo=
    
    return subArreglo


### Prueba manuealmente tu respuesta

In [ ]:
import student_PS2_NUMPY_5 as st
reload(st)
X=np.array([ 0.79035627,  0.08409479,  0.57376371,  0.8449833 ,  0.63291871,  0.78611748,
  0.65485656  ,0.6580865   ,0.80133703  ,0.6094324   ,0.62010416  ,0.98148802,
  0.70262324  ,0.42894768  ,0.70470542  ,0.37187055  ,0.05427004  ,0.50294194,
  0.84034571  ,0.00586813])
c=10
l=5

st.subArray(X,c,l)