In [1]:
import numpy as np
import matplotlib.pyplot as plot
import tensorflow as tf
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
%matplotlib inline

/opt/conda/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## Cargamos el dataset

observa cómo convertimos la variable $y$ en **categórica**

In [2]:
mnist = np.loadtxt("data/mnist1.5k.csv", delimiter=",")
print "dimension de los datos originales", mnist.shape
X=mnist[:,1:785]
y=mnist[:,0]
yc = tf.keras.utils.to_categorical(y)
print X.shape, y.shape, yc.shape

Xtr, Xts, ytr, yts = train_test_split(X,yc,test_size=.3)
print Xtr.shape, ytr.shape, Xts.shape, yts.shape

dimension de los datos originales (1500, 785)
(1500, 784) (1500,) (1500, 10)
(1050, 784) (1050, 10) (450, 784) (450, 10)


In [3]:
print y[:5]

[1. 0. 1. 4. 0.]


In [4]:
print yc[:5]

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Creamos el modelo con  `keras`

observa el número de parámetros

In [12]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten

In [13]:
def get_model_A():
    tf.keras.backend.clear_session()
    model = Sequential()
    model.add(Dense(100, activation='tanh', input_dim=784))
    model.add(Dense(200, activation='tanh'))
    model.add(Dense(500, activation='tanh'))
    model.add(Dense(200, activation='tanh'))
    model.add(Dense(200, activation='tanh'))
    model.add(Dense(10, activation='softmax'))
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    model.reset_states()
    return model

model = get_model_A()
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               78500     
_________________________________________________________________
dense_1 (Dense)              (None, 200)               20200     
_________________________________________________________________
dense_2 (Dense)              (None, 500)               100500    
_________________________________________________________________
dense_3 (Dense)              (None, 200)               100200    
_________________________________________________________________
dense_4 (Dense)              (None, 200)               40200     
_________________________________________________________________
dense_5 (Dense)              (None, 10)                2010      
Total params: 341,610
Trainable params: 341,610
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [15]:
model.fit(Xtr, ytr, epochs=40, batch_size=64, validation_data=(Xts, yts))


Train on 1050 samples, validate on 450 samples
Epoch 1/40
1050/1050 [==============================] - 2s 2ms/step - loss: 1.3141 - acc: 0.5629 - val_loss: 0.8457 - val_acc: 0.7289
Epoch 2/40
1050/1050 [==============================] - 0s 456us/step - loss: 0.7186 - acc: 0.7657 - val_loss: 0.7762 - val_acc: 0.7444
Epoch 3/40
1050/1050 [==============================] - 0s 448us/step - loss: 0.5812 - acc: 0.8067 - val_loss: 0.7163 - val_acc: 0.7822
Epoch 4/40
1050/1050 [==============================] - 0s 453us/step - loss: 0.4898 - acc: 0.8533 - val_loss: 0.6664 - val_acc: 0.7956
Epoch 5/40
1050/1050 [==============================] - 0s 462us/step - loss: 0.4504 - acc: 0.8619 - val_loss: 0.6648 - val_acc: 0.7711
Epoch 6/40
1050/1050 [==============================] - 0s 468us/step - loss: 0.4024 - acc: 0.8705 - val_loss: 0.6614 - val_acc: 0.7956
Epoch 7/40
1050/1050 [==============================] - 1s 506us/step - loss: 0.3983 - acc: 0.8629 - val_loss: 0.7287 - val_acc: 0.7800
Epo

## Añadimos capas de regularización

In [9]:
def get_model_B():
    tf.keras.backend.clear_session()
    model = Sequential()
    model.add(Dense(100, activation='tanh', input_dim=784))
    model.add(Dropout(0.15))
    model.add(Dense(200, activation='tanh'))
    model.add(Dropout(0.15))
    model.add(Dense(500, activation='tanh'))
    model.add(Dropout(0.15))
    model.add(Dense(200, activation='tanh'))
    model.add(Dropout(0.4))
    model.add(Dense(200, activation='tanh'))
    model.add(Dropout(0.4))
    model.add(Dense(10, activation='softmax'))
    model.compile(optimizer='adam',
                  loss='categorical_crossentropy',
                  metrics=['accuracy'])
    model.reset_states()
    return model

model = get_model_B()
model.summary()


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               78500     
_________________________________________________________________
dropout (Dropout)            (None, 100)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 200)               20200     
_________________________________________________________________
dropout_1 (Dropout)          (None, 200)               0         
_________________________________________________________________
dense_2 (Dense)              (None, 500)               100500    
_________________________________________________________________
dropout_2 (Dropout)          (None, 500)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 200)               100200    
__________

In [10]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [11]:
model.fit(Xtr, ytr,
         batch_size=64,
         epochs=50,
         validation_data=(Xts, yts))

Train on 1050 samples, validate on 450 samples
Epoch 1/50
1050/1050 [==============================] - 3s 3ms/step - loss: 1.8647 - acc: 0.3562 - val_loss: 1.2516 - val_acc: 0.5667
Epoch 2/50
1050/1050 [==============================] - 1s 686us/step - loss: 1.1837 - acc: 0.6029 - val_loss: 0.8837 - val_acc: 0.6911
Epoch 3/50
1050/1050 [==============================] - 1s 696us/step - loss: 1.0214 - acc: 0.6571 - val_loss: 0.7864 - val_acc: 0.7156
Epoch 4/50
1050/1050 [==============================] - 1s 618us/step - loss: 0.9505 - acc: 0.6848 - val_loss: 0.8401 - val_acc: 0.7089
Epoch 5/50
1050/1050 [==============================] - 1s 778us/step - loss: 0.8440 - acc: 0.7010 - val_loss: 0.7276 - val_acc: 0.7556
Epoch 6/50
1050/1050 [==============================] - 1s 731us/step - loss: 0.8004 - acc: 0.7390 - val_loss: 0.6876 - val_acc: 0.8022
Epoch 7/50
1050/1050 [==============================] - 1s 671us/step - loss: 0.7860 - acc: 0.7333 - val_loss: 0.6326 - val_acc: 0.7911
Epo